### ISSUE TITLE
How would you save the url of each page in the breadcrumb array in order to have the breadcrumbs link back to their page?

### ISSUE THREAD

**Issue by michaelparkadze** [ocanzillon/angular-breadcrumb#1]
Hi :)

**Comment by ocanzillon** [comment]
Hi Michael,

Thanks for your request. Actually, I had this improvement in mind.
I would modify the Breadcrumb model to add a "url: string" property and compute this property from the route object in the BreadcrumbService. Then the HTML template from the BreadcrumbComponent would use the new url property to display a link.
I will probably commit something in the next few days regarding this feature request ;-)

Best regards,

Olivier

**Comment by ocanzillon** [comment]
Hi Michael,

Please have a look at the repository. It contains your feature request now.

Best regards,

Olivier

**Comment by michaelparkadze** [comment]
Thanks, much appreciated ;)
